# Introduction

* List one
* Two 

# Some awesome code

    print('hello world')

    while(1)

# ../sketchnote/Distance_Comm.png

# Two columns

===1

! ../sketchnote/Packets.png

===2

    print('hello world')
    while(1)

# ../sketchnote/Store_Fwd.png

<section>
===1
<pre><code>if ( i < 100 ) {
   echo("small");
}
</code></pre>
===2
! ../images/iso-tcp.svg
</section>

<section data-background="../images/iso-tcp.svg"
    data-background-size="contain">
</section>

