<section>
<pre><code>if ( i < 100 ) {
   echo("small");
}
</code></pre>
</section>

<section>
<div style='float:left;width:50%;' class='centered'>
<pre><code>if ( i < 100 ) {
   echo("small");
}
</code></pre>
</div>
<div style='float:right;width:50%;padding-right:0px;'>
<img src="../images/iso-tcp.svg" >
</div>
<br clear="all">
</section>
<section data-background="../sketchnote/Traveling_Packets.png" 
    data-background-size="95%">
</section>
<section data-background="../images/iso-tcp.svg"
    data-background-size="95%">
</section>
