<section>
<h2>Sample Slides for net-intro</h2>
<p>This is just a few slides to test out
the basic slide styles.  
</p>
<p>
A fun feature is
that you can scribble on these slides using
<a href="http://csev.github.io/dazzleSketch/" target="_blank">
DazzleSketch</a>.  The Control key plus 
numbers change colors and the Control-backquote clears the scribbles.
See the DazzleSketch web site for more details.
</p>
<br clear="all">
</section>
<section>
<h2>Sample Things</h2>
<ul>
<li>A full-screen image</li>
<li>A two-column page</li>
<li>A full-screen SVG image</li>
</ul>
</section>
<section data-background="../sketchnote/Traveling_Packets.png" 
    data-background-size="contain">
</section>
<section>
<div style='float:left;width:50%;' class='centered'>
<pre><code>if ( i < 100 ) {
   echo("small");
}
</code></pre>
</div>
<div style='float:right;width:50%;padding-right:0px;'>
<img src="../images/iso-tcp.svg" >
</div>
</section>
<section data-background="../images/iso-tcp.svg"
    data-background-size="contain">
</section>
